/* Shared site settings. OWNER CONFIRMATION: email spelling differed across legacy pages; this uses the clinic name consistently. */
const CLINIC={name:'100SMILES Dental Care',phone:'07 5000 5599',email:'100smiles@gmail.com',address:'33 Fantail Street, Razole, Queensland',hours:'Mon–Fri 8:30am–6:30pm · Sat–Sun 8:30am–1:00pm'};
document.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('[data-clinic]').forEach(el=>{const key=el.dataset.clinic;el.textContent=CLINIC[key]||'';if(el.tagName==='A')el.href=key==='email'?`mailto:${CLINIC.email}`:key==='phone'?`tel:${CLINIC.phone.replace(/\s/g,'')}`:el.href});
 document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
 const header=document.querySelector('.site-header'),toggle=document.querySelector('.nav-toggle'),nav=document.querySelector('.nav-links');
 const closeMenu=()=>{nav?.classList.remove('open');toggle?.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')};
 toggle?.addEventListener('click',()=>{const open=!nav.classList.contains('open');nav.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
 const onScroll=()=>{header?.classList.toggle('scrolled',scrollY>12);document.querySelector('.back-top')?.classList.toggle('show',scrollY>500)};addEventListener('scroll',onScroll,{passive:true});onScroll();document.querySelector('.back-top')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
 const page=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav-links a').forEach(a=>{if(a.getAttribute('href')===page){a.classList.add('active');a.setAttribute('aria-current','page')}});
 const observer='IntersectionObserver'in window?new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12}):null;document.querySelectorAll('.reveal').forEach(el=>observer?observer.observe(el):el.classList.add('visible'));
 document.querySelectorAll('img').forEach(img=>{img.loading='lazy';img.addEventListener('error',()=>{img.alt=`${img.alt} (image unavailable)`;img.classList.add('image-error')},{once:true})});
 document.querySelectorAll('[data-filter-group]').forEach(group=>{const target=group.dataset.filterGroup;group.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{group.querySelectorAll('button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll(`[data-${target}]`).forEach(card=>card.classList.toggle('hidden',btn.dataset.filter!=='all'&&card.dataset[target]!==btn.dataset.filter))}))});
 const search=document.querySelector('#articleSearch');const filterArticles=()=>{const q=search?.value.toLowerCase()||'',active=document.querySelector('[data-filter-group="category"] .active')?.dataset.filter||'all';document.querySelectorAll('[data-category]').forEach(c=>c.classList.toggle('hidden',!(c.textContent.toLowerCase().includes(q)&&(active==='all'||c.dataset.category===active))))};search?.addEventListener('input',filterArticles);document.querySelectorAll('[data-filter-group="category"] button').forEach(b=>b.addEventListener('click',filterArticles));
 const expired=document.querySelector('#expiredPromotions');document.querySelectorAll('[data-expiry]').forEach(card=>{if(new Date(`${card.dataset.expiry}T23:59:59`)<new Date()){card.querySelector('.status').textContent='Offer Ended';card.querySelector('.status').classList.add('expired');card.querySelector('.promo-action')?.setAttribute('hidden','');expired?.append(card)}});
 setupDemoForm('#newsletterForm','Newsletter sign-up is a demonstration; no subscription was stored.');setupDemoForm('#contactForm','Your message was validated, but this demonstration site did not send it. Please phone or email the clinic.');setupBooking();
});
function setupDemoForm(selector,message){const form=document.querySelector(selector);if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const alert=form.querySelector('.alert');if(!form.checkValidity()){form.reportValidity();return}const btn=form.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Checking…';setTimeout(()=>{btn.disabled=false;btn.textContent=btn.dataset.label||'Submit';alert.textContent=message;alert.hidden=false;alert.focus()},450)})}
function setupBooking(){const form=document.querySelector('#bookingForm');if(!form)return;const date=form.querySelector('#date');date.min=new Date().toISOString().split('T')[0];form.querySelectorAll('input,select,textarea').forEach(f=>f.addEventListener('blur',()=>validate(f)));form.addEventListener('submit',e=>{e.preventDefault();const fields=[...form.querySelectorAll('[required]')],ok=fields.every(validate);if(!ok){form.querySelector('.invalid')?.focus();return}const data=new FormData(form),summary=document.querySelector('#bookingSummary');summary.innerHTML=`<h2>Appointment request summary</h2><p><strong>Patient:</strong> ${safe(data.get('fullName'))}</p><p><strong>Service:</strong> ${safe(form.service.options[form.service.selectedIndex].text)}</p><p><strong>Date and time:</strong> ${safe(data.get('date'))}, ${safe(form.time.options[form.time.selectedIndex].text)}</p><p><strong>Preferred dentist:</strong> ${safe(form.dentist.options[form.dentist.selectedIndex].text)}</p><div class="notice">This is a front-end demonstration. No appointment was submitted. Please contact the clinic to confirm.</div><button class="btn" type="button" id="bookAgain">Book another appointment</button>`;form.hidden=true;summary.hidden=false;summary.focus();document.querySelector('#bookAgain').onclick=()=>{form.reset();form.hidden=false;summary.hidden=true;form.querySelector('input').focus()}})}
function validate(f){const err=f.closest('.field')?.querySelector('.error-text');let msg='';if(!f.validity.valid)msg=f.validity.valueMissing?'This field is required.':f.validity.typeMismatch?'Enter a valid value.':f.validationMessage;f.classList.toggle('invalid',!!msg);f.setAttribute('aria-invalid',String(!!msg));if(err)err.textContent=msg;return!msg}function safe(v){const d=document.createElement('div');d.textContent=v||'No preference';return d.innerHTML}
